import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";
import {
  LucideAngularModule,
  BarChart3,
  Users,
  Globe,
  TrendingUp,
  Award,
  Heart,
  DollarSign,
  Briefcase,
} from "lucide-angular";

@Component({
  selector: "app-impact",
  standalone: true,
  imports: [RouterLink, LucideAngularModule],
  template: `
    <!-- Hero Section -->
    <section
      class="section-padding bg-gradient-to-br from-purple-50 via-white to-cyan-50"
    >
      <div class="container-max">
        <div class="text-center max-w-4xl mx-auto">
          <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Our <span class="gradient-text">Impact</span>
          </h1>
          <p class="text-xl text-gray-600 mb-8">
            Measuring the real difference we're making in women's lives and
            communities around the world through data-driven insights and
            powerful stories.
          </p>
        </div>
      </div>
    </section>

    <!-- Key Metrics -->
    <section class="section-padding bg-white">
      <div class="container-max">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Impact by the <span class="gradient-text">Numbers</span>
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            A decade of dedication has yielded measurable results across all our
            programs.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div class="text-center animate-fade-in-up">
            <div
              class="w-20 h-20 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="users"
                class="w-10 h-10 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">10,423</h3>
            <p class="text-gray-600 font-medium">Women Empowered</p>
            <p class="text-sm text-gray-500 mt-2">
              Direct program participants
            </p>
          </div>

          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.1s"
          >
            <div
              class="w-20 h-20 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="globe"
                class="w-10 h-10 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">25</h3>
            <p class="text-gray-600 font-medium">Countries Reached</p>
            <p class="text-sm text-gray-500 mt-2">Global presence and impact</p>
          </div>

          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.2s"
          >
            <div
              class="w-20 h-20 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="briefcase"
                class="w-10 h-10 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">3,847</h3>
            <p class="text-gray-600 font-medium">Jobs Created</p>
            <p class="text-sm text-gray-500 mt-2">Through our programs</p>
          </div>

          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.3s"
          >
            <div
              class="w-20 h-20 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="dollar-sign"
                class="w-10 h-10 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">$12.5M</h3>
            <p class="text-gray-600 font-medium">Economic Impact</p>
            <p class="text-sm text-gray-500 mt-2">Generated by participants</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Success Stories -->
    <section class="section-padding bg-gray-50">
      <div class="container-max">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Success <span class="gradient-text">Stories</span>
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            Real stories from women whose lives have been transformed through
            our programs.
          </p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-12">
          <!-- Story 1 -->
          <div class="card p-8 animate-fade-in-up">
            <div class="flex items-center mb-6">
              <img
                src="https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80"
                alt="Sarah Johnson"
                class="w-16 h-16 rounded-full object-cover mr-4"
              />
              <div>
                <h3 class="text-xl font-semibold text-gray-900">
                  Sarah Johnson
                </h3>
                <p class="text-purple-600 font-medium">Tech Entrepreneur</p>
                <p class="text-sm text-gray-500">Lagos, Nigeria</p>
              </div>
            </div>
            <blockquote class="text-gray-600 mb-6 italic">
              "The Women in Tech Leaders program changed my life completely. I
              went from being unemployed to founding a fintech startup that now
              employs 15 people. The mentorship and technical training gave me
              the confidence to pursue my dreams."
            </blockquote>
            <div class="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p class="font-semibold text-gray-900">Program</p>
                <p class="text-gray-600">Tech Leaders 2022</p>
              </div>
              <div>
                <p class="font-semibold text-gray-900">Achievement</p>
                <p class="text-gray-600">Founded TechFin Solutions</p>
              </div>
            </div>
          </div>

          <!-- Story 2 -->
          <div
            class="card p-8 animate-fade-in-up"
            style="animation-delay: 0.1s"
          >
            <div class="flex items-center mb-6">
              <img
                src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80"
                alt="Maria Rodriguez"
                class="w-16 h-16 rounded-full object-cover mr-4"
              />
              <div>
                <h3 class="text-xl font-semibold text-gray-900">
                  Maria Rodriguez
                </h3>
                <p class="text-purple-600 font-medium">Community Leader</p>
                <p class="text-sm text-gray-500">Guatemala City, Guatemala</p>
              </div>
            </div>
            <blockquote class="text-gray-600 mb-6 italic">
              "Through the Leadership Development program, I found my voice and
              learned to advocate for my community. I'm now the mayor of my town
              and have implemented programs that have improved healthcare access
              for over 5,000 women."
            </blockquote>
            <div class="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p class="font-semibold text-gray-900">Program</p>
                <p class="text-gray-600">Leadership Dev 2020</p>
              </div>
              <div>
                <p class="font-semibold text-gray-900">Achievement</p>
                <p class="text-gray-600">Elected Mayor</p>
              </div>
            </div>
          </div>

          <!-- Story 3 -->
          <div
            class="card p-8 animate-fade-in-up"
            style="animation-delay: 0.2s"
          >
            <div class="flex items-center mb-6">
              <img
                src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80"
                alt="Priya Sharma"
                class="w-16 h-16 rounded-full object-cover mr-4"
              />
              <div>
                <h3 class="text-xl font-semibold text-gray-900">
                  Priya Sharma
                </h3>
                <p class="text-purple-600 font-medium">
                  Social Enterprise Founder
                </p>
                <p class="text-sm text-gray-500">Mumbai, India</p>
              </div>
            </div>
            <blockquote class="text-gray-600 mb-6 italic">
              "The Entrepreneurship program helped me turn my passion for
              sustainable fashion into a thriving business. My company now
              employs 50 women from rural areas, providing them with stable
              income and skills training."
            </blockquote>
            <div class="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p class="font-semibold text-gray-900">Program</p>
                <p class="text-gray-600">Entrepreneurship 2021</p>
              </div>
              <div>
                <p class="font-semibold text-gray-900">Achievement</p>
                <p class="text-gray-600">Green Fashion Co.</p>
              </div>
            </div>
          </div>

          <!-- Story 4 -->
          <div
            class="card p-8 animate-fade-in-up"
            style="animation-delay: 0.3s"
          >
            <div class="flex items-center mb-6">
              <img
                src="https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80"
                alt="Fatima Al-Zahra"
                class="w-16 h-16 rounded-full object-cover mr-4"
              />
              <div>
                <h3 class="text-xl font-semibold text-gray-900">
                  Fatima Al-Zahra
                </h3>
                <p class="text-purple-600 font-medium">Doctor</p>
                <p class="text-sm text-gray-500">Amman, Jordan</p>
              </div>
            </div>
            <blockquote class="text-gray-600 mb-6 italic">
              "The Education Access scholarship enabled me to complete my
              medical degree. Today, I run a clinic that provides free
              healthcare to women in my community. Education truly is the key to
              breaking cycles of poverty."
            </blockquote>
            <div class="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p class="font-semibold text-gray-900">Program</p>
                <p class="text-gray-600">Education Access 2019</p>
              </div>
              <div>
                <p class="font-semibold text-gray-900">Achievement</p>
                <p class="text-gray-600">Community Health Clinic</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Program Impact Breakdown -->
    <section class="section-padding bg-white">
      <div class="container-max">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Program <span class="gradient-text">Breakdown</span>
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            Detailed impact metrics across our core program areas.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <!-- Education Impact -->
          <div class="card p-8 text-center animate-fade-in-up">
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="trending-up"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-2xl font-bold text-gray-900 mb-4">
              Education Programs
            </h3>
            <div class="space-y-4">
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Scholarships Awarded</span>
                <span class="font-semibold text-gray-900">2,847</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Graduation Rate</span>
                <span class="font-semibold text-gray-900">94%</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Career Advancement</span>
                <span class="font-semibold text-gray-900">89%</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Income Increase</span>
                <span class="font-semibold text-gray-900">156%</span>
              </div>
            </div>
          </div>

          <!-- Leadership Impact -->
          <div
            class="card p-8 text-center animate-fade-in-up"
            style="animation-delay: 0.1s"
          >
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="award"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-2xl font-bold text-gray-900 mb-4">
              Leadership Development
            </h3>
            <div class="space-y-4">
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Leaders Trained</span>
                <span class="font-semibold text-gray-900">1,234</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Promotion Rate</span>
                <span class="font-semibold text-gray-900">76%</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Board Positions</span>
                <span class="font-semibold text-gray-900">145</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Public Offices</span>
                <span class="font-semibold text-gray-900">23</span>
              </div>
            </div>
          </div>

          <!-- Entrepreneurship Impact -->
          <div
            class="card p-8 text-center animate-fade-in-up"
            style="animation-delay: 0.2s"
          >
            <div
              class="w-16 h-16 gradient-bg rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <lucide-icon
                name="briefcase"
                class="w-8 h-8 text-white"
              ></lucide-icon>
            </div>
            <h3 class="text-2xl font-bold text-gray-900 mb-4">
              Entrepreneurship
            </h3>
            <div class="space-y-4">
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Businesses Launched</span>
                <span class="font-semibold text-gray-900">1,156</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Survival Rate (2+ years)</span>
                <span class="font-semibold text-gray-900">84%</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Jobs Created</span>
                <span class="font-semibold text-gray-900">3,847</span>
              </div>
              <div class="flex justify-between items-center">
                <span class="text-gray-600">Revenue Generated</span>
                <span class="font-semibold text-gray-900">$8.2M</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Global Reach -->
    <section class="section-padding bg-gray-50">
      <div class="container-max">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Global <span class="gradient-text">Reach</span>
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            Our impact spans across continents, reaching women in diverse
            communities worldwide.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8">
          <div class="text-center animate-fade-in-up">
            <h3 class="text-2xl font-bold text-gray-900 mb-2">Africa</h3>
            <p class="text-gray-600 mb-2">8 countries</p>
            <p class="text-3xl font-bold gradient-text">3,245</p>
            <p class="text-sm text-gray-500">women empowered</p>
          </div>
          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.1s"
          >
            <h3 class="text-2xl font-bold text-gray-900 mb-2">Asia</h3>
            <p class="text-gray-600 mb-2">7 countries</p>
            <p class="text-3xl font-bold gradient-text">2,891</p>
            <p class="text-sm text-gray-500">women empowered</p>
          </div>
          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.2s"
          >
            <h3 class="text-2xl font-bold text-gray-900 mb-2">Latin America</h3>
            <p class="text-gray-600 mb-2">6 countries</p>
            <p class="text-3xl font-bold gradient-text">2,567</p>
            <p class="text-sm text-gray-500">women empowered</p>
          </div>
          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.3s"
          >
            <h3 class="text-2xl font-bold text-gray-900 mb-2">Middle East</h3>
            <p class="text-gray-600 mb-2">3 countries</p>
            <p class="text-3xl font-bold gradient-text">1,234</p>
            <p class="text-sm text-gray-500">women empowered</p>
          </div>
          <div
            class="text-center animate-fade-in-up"
            style="animation-delay: 0.4s"
          >
            <h3 class="text-2xl font-bold text-gray-900 mb-2">Europe</h3>
            <p class="text-gray-600 mb-2">1 country</p>
            <p class="text-3xl font-bold gradient-text">486</p>
            <p class="text-sm text-gray-500">women empowered</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section
      class="section-padding bg-gradient-to-r from-purple-600 to-cyan-500 text-white"
    >
      <div class="container-max text-center">
        <h2 class="text-3xl md:text-4xl font-bold mb-4">
          Be Part of Our Impact
        </h2>
        <p class="text-lg mb-8 max-w-2xl mx-auto opacity-90">
          Every donation, every volunteer hour, and every partnership
          contributes to the incredible impact we're making in women's lives
          around the world.
        </p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <a
            routerLink="/donate"
            class="btn-primary bg-white text-purple-600 hover:bg-gray-100"
          >
            <lucide-icon name="heart" class="w-5 h-5 mr-2"></lucide-icon>
            Make a Donation
          </a>
          <a
            routerLink="/contact"
            class="btn-secondary border-white text-white hover:bg-white hover:text-purple-600"
          >
            Get Involved
          </a>
        </div>
      </div>
    </section>
  `,
})
export class ImpactComponent {
  readonly BarChart3 = BarChart3;
  readonly Users = Users;
  readonly Globe = Globe;
  readonly TrendingUp = TrendingUp;
  readonly Award = Award;
  readonly Heart = Heart;
  readonly DollarSign = DollarSign;
  readonly Briefcase = Briefcase;
}
