import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";

@Component({
  selector: "app-impact",
  standalone: true,
  imports: [RouterLink],
  template: `
    <!-- Hero Section -->
    <section
      class="py-16 px-8 bg-gradient-to-br from-purple-50 via-white to-cyan-50"
    >
      <div class="max-w-6xl mx-auto">
        <div class="text-center max-w-4xl mx-auto">
          <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Our
            <span
              class="bg-gradient-to-r from-purple-600 via-cyan-500 to-green-500 bg-clip-text text-transparent"
              >Impact</span
            >
          </h1>
          <p class="text-xl text-gray-600 mb-8">
            Measuring the real difference we're making in women's lives and
            communities around the world through data-driven insights and
            powerful stories.
          </p>
        </div>
      </div>
    </section>

    <!-- Key Metrics -->
    <section class="py-16 px-8 bg-white">
      <div class="max-w-6xl mx-auto">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Impact by the
            <span
              class="bg-gradient-to-r from-purple-600 via-cyan-500 to-green-500 bg-clip-text text-transparent"
              >Numbers</span
            >
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            A decade of dedication has yielded measurable results across all our
            programs.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div class="text-center">
            <div
              class="w-20 h-20 bg-gradient-to-r from-purple-600 to-cyan-500 rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <span class="text-white text-3xl">👥</span>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">10,423</h3>
            <p class="text-gray-600 font-medium">Women Empowered</p>
            <p class="text-sm text-gray-500 mt-2">
              Direct program participants
            </p>
          </div>

          <div class="text-center">
            <div
              class="w-20 h-20 bg-gradient-to-r from-purple-600 to-cyan-500 rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <span class="text-white text-3xl">🌍</span>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">25</h3>
            <p class="text-gray-600 font-medium">Countries Reached</p>
            <p class="text-sm text-gray-500 mt-2">Global presence and impact</p>
          </div>

          <div class="text-center">
            <div
              class="w-20 h-20 bg-gradient-to-r from-purple-600 to-cyan-500 rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <span class="text-white text-3xl">💼</span>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">3,847</h3>
            <p class="text-gray-600 font-medium">Jobs Created</p>
            <p class="text-sm text-gray-500 mt-2">Through our programs</p>
          </div>

          <div class="text-center">
            <div
              class="w-20 h-20 bg-gradient-to-r from-purple-600 to-cyan-500 rounded-full flex items-center justify-center mx-auto mb-6"
            >
              <span class="text-white text-3xl">💰</span>
            </div>
            <h3 class="text-4xl font-bold text-gray-900 mb-2">&#36;12.5M</h3>
            <p class="text-gray-600 font-medium">Economic Impact</p>
            <p class="text-sm text-gray-500 mt-2">Generated by participants</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Success Stories -->
    <section class="py-16 px-8 bg-gray-50">
      <div class="max-w-6xl mx-auto">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Success
            <span
              class="bg-gradient-to-r from-purple-600 via-cyan-500 to-green-500 bg-clip-text text-transparent"
              >Stories</span
            >
          </h2>
          <p class="text-lg text-gray-600 max-w-2xl mx-auto">
            Real stories from women whose lives have been transformed through
            our programs.
          </p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-12">
          <!-- Story 1 -->
          <div class="bg-white rounded-lg shadow-md p-8">
            <div class="flex items-center mb-6">
              <img
                src="https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80"
                alt="Sarah Johnson"
                class="w-16 h-16 rounded-full object-cover mr-4"
              />
              <div>
                <h3 class="text-xl font-semibold text-gray-900">
                  Sarah Johnson
                </h3>
                <p class="text-purple-600 font-medium">Tech Entrepreneur</p>
                <p class="text-sm text-gray-500">Lagos, Nigeria</p>
              </div>
            </div>
            <blockquote class="text-gray-600 mb-6 italic">
              "The Women in Tech Leaders program changed my life completely. I
              went from being unemployed to founding a fintech startup that now
              employs 15 people. The mentorship and technical training gave me
              the confidence to pursue my dreams."
            </blockquote>
          </div>

          <!-- Story 2 -->
          <div class="bg-white rounded-lg shadow-md p-8">
            <div class="flex items-center mb-6">
              <img
                src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=80"
                alt="Maria Rodriguez"
                class="w-16 h-16 rounded-full object-cover mr-4"
              />
              <div>
                <h3 class="text-xl font-semibold text-gray-900">
                  Maria Rodriguez
                </h3>
                <p class="text-purple-600 font-medium">Community Leader</p>
                <p class="text-sm text-gray-500">Guatemala City, Guatemala</p>
              </div>
            </div>
            <blockquote class="text-gray-600 mb-6 italic">
              "Through the Leadership Development program, I found my voice and
              learned to advocate for my community. I'm now the mayor of my town
              and have implemented programs that have improved healthcare access
              for over 5,000 women."
            </blockquote>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section
      class="py-16 px-8 bg-gradient-to-r from-purple-600 to-cyan-500 text-white"
    >
      <div class="max-w-6xl mx-auto text-center">
        <h2 class="text-3xl md:text-4xl font-bold mb-4">
          Be Part of Our Impact
        </h2>
        <p class="text-lg mb-8 max-w-2xl mx-auto opacity-90">
          Every donation, every volunteer hour, and every partnership
          contributes to the incredible impact we're making in women's lives
          around the world.
        </p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <a
            routerLink="/donate"
            class="inline-flex items-center justify-center px-6 py-3 text-base font-medium bg-white text-purple-600 rounded-lg hover:bg-gray-100"
          >
            ♥ Make a Donation
          </a>
          <a
            routerLink="/contact"
            class="inline-flex items-center justify-center px-6 py-3 text-base font-medium border border-white text-white rounded-lg hover:bg-white hover:text-purple-600"
          >
            Get Involved
          </a>
        </div>
      </div>
    </section>
  `,
})
export class ImpactComponent {}
